//! Extract C fences from Markdown, compile them as one translation unit, and
//! optionally run a document-specific test harness.
//!
//! This tool intentionally has no crate dependencies so it can be built with
//! `rustc tools/docs/verify_markdown_c.rs -o .tmp/verify-markdown-c`.

use std::env;
use std::ffi::OsString;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::{Command, ExitCode};

#[derive(Debug, PartialEq, Eq)]
struct CBlock {
    start_line: usize,
    code: String,
}

#[derive(Debug, PartialEq, Eq)]
enum Fence {
    C {
        start_line: usize,
        lines: Vec<String>,
    },
    Other,
}

#[derive(Debug)]
struct Options {
    compiler: PathBuf,
    runner: Option<PathBuf>,
    harness: Option<PathBuf>,
    output_dir: PathBuf,
    markdown: PathBuf,
}

fn extract_c_blocks(content: &str) -> Result<Vec<CBlock>, String> {
    let mut blocks = Vec::new();
    let mut fence: Option<Fence> = None;

    for (index, line) in content.lines().enumerate() {
        let line_number = index + 1;
        let trimmed = line.trim();

        match &mut fence {
            None if trimmed == "```c" => {
                fence = Some(Fence::C {
                    start_line: line_number + 1,
                    lines: Vec::new(),
                });
            }
            None if trimmed.starts_with("```") => {
                fence = Some(Fence::Other);
            }
            Some(Fence::C { start_line, lines }) if trimmed == "```" => {
                blocks.push(CBlock {
                    start_line: *start_line,
                    code: lines.join("\n"),
                });
                fence = None;
            }
            Some(Fence::Other) if trimmed == "```" => {
                fence = None;
            }
            Some(Fence::C { lines, .. }) => lines.push(line.to_owned()),
            Some(Fence::Other) | None => {}
        }
    }

    match fence {
        Some(Fence::C { start_line, .. }) => {
            Err(format!("unclosed C fence beginning at line {start_line}"))
        }
        Some(Fence::Other) => Err("unclosed non-C fence".to_owned()),
        None => Ok(blocks),
    }
}

fn c_string_path(path: &Path) -> String {
    path.display()
        .to_string()
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
}

fn render_translation_unit(
    markdown: &Path,
    blocks: &[CBlock],
    harness: Option<(&Path, &str)>,
) -> String {
    let mut output = String::from("/* Generated by tools/docs/verify_markdown_c.rs. */\n");
    let markdown_name = c_string_path(markdown);

    for block in blocks {
        output.push_str(&format!(
            "\n#line {} \"{}\"\n{}\n",
            block.start_line, markdown_name, block.code
        ));
    }

    if let Some((path, content)) = harness {
        output.push_str(&format!(
            "\n#line 1 \"{}\"\n{}\n",
            c_string_path(path),
            content
        ));
    }
    output
}

fn take_value(
    arguments: &mut impl Iterator<Item = OsString>,
    option: &str,
) -> Result<PathBuf, String> {
    arguments
        .next()
        .map(PathBuf::from)
        .ok_or_else(|| format!("{option} requires a path"))
}

fn parse_options() -> Result<Options, String> {
    let mut compiler = None;
    let mut runner = None;
    let mut harness = None;
    let mut output_dir = PathBuf::from(".tmp/verify-markdown-c");
    let mut markdown = None;
    let mut arguments = env::args_os().skip(1);

    while let Some(argument) = arguments.next() {
        match argument.to_str() {
            Some("--compiler") => {
                compiler = Some(take_value(&mut arguments, "--compiler")?);
            }
            Some("--runner") => {
                runner = Some(take_value(&mut arguments, "--runner")?);
            }
            Some("--harness") => {
                harness = Some(take_value(&mut arguments, "--harness")?);
            }
            Some("--output-dir") => {
                output_dir = take_value(&mut arguments, "--output-dir")?;
            }
            Some("-h" | "--help") => return Err(String::new()),
            Some(value) if value.starts_with('-') => {
                return Err(format!("unknown option: {value}"));
            }
            _ if markdown.is_none() => markdown = Some(PathBuf::from(argument)),
            _ => return Err("only one Markdown file may be supplied".to_owned()),
        }
    }

    let compiler = compiler.ok_or_else(|| "--compiler is required".to_owned())?;
    let markdown = markdown.ok_or_else(|| "Markdown file is required".to_owned())?;
    if runner.is_some() && harness.is_none() {
        return Err("--runner requires --harness".to_owned());
    }

    Ok(Options {
        compiler,
        runner,
        harness,
        output_dir,
        markdown,
    })
}

fn usage() {
    eprintln!(
        "usage: verify_markdown_c --compiler PATH [--harness PATH --runner PATH] \
         [--output-dir DIR] <markdown-file>"
    );
}

fn run(options: Options) -> Result<(), String> {
    let markdown_content = fs::read_to_string(&options.markdown)
        .map_err(|error| format!("{}: {error}", options.markdown.display()))?;
    let blocks = extract_c_blocks(&markdown_content)?;
    if blocks.is_empty() {
        return Err(format!(
            "{}: no ```c fences found",
            options.markdown.display()
        ));
    }

    let harness_content = options
        .harness
        .as_ref()
        .map(|path| {
            fs::read_to_string(path)
                .map(|content| (path.as_path(), content))
                .map_err(|error| format!("{}: {error}", path.display()))
        })
        .transpose()?;
    let harness = harness_content
        .as_ref()
        .map(|(path, content)| (*path, content.as_str()));

    fs::create_dir_all(&options.output_dir)
        .map_err(|error| format!("{}: {error}", options.output_dir.display()))?;
    let stem = options
        .markdown
        .file_stem()
        .and_then(|value| value.to_str())
        .unwrap_or("markdown-c");
    let source = options.output_dir.join(format!("{stem}.combined.c"));
    let executable = options.output_dir.join(format!("{stem}.filc-test"));
    fs::write(
        &source,
        render_translation_unit(&options.markdown, &blocks, harness),
    )
    .map_err(|error| format!("{}: {error}", source.display()))?;

    let status = Command::new(&options.compiler)
        .args([
            "-std=c11",
            "-O2",
            "-g",
            "-Wall",
            "-Wextra",
            "-Werror",
            "-Wno-unused-function",
        ])
        .arg(&source)
        .arg("-lm")
        .arg("-o")
        .arg(&executable)
        .status()
        .map_err(|error| {
            format!(
                "failed to invoke compiler {}: {error}",
                options.compiler.display()
            )
        })?;
    if !status.success() {
        return Err(format!("C compilation failed with {status}"));
    }

    println!(
        "compiled {} C fences from {}",
        blocks.len(),
        options.markdown.display()
    );

    if let Some(runner) = options.runner {
        let status = Command::new(&runner)
            .arg(&executable)
            .status()
            .map_err(|error| format!("failed to invoke runner {}: {error}", runner.display()))?;
        if !status.success() {
            return Err(format!("C tests failed with {status}"));
        }
        println!("runtime tests passed: {}", executable.display());
    }

    Ok(())
}

fn main() -> ExitCode {
    let options = match parse_options() {
        Ok(options) => options,
        Err(error) => {
            usage();
            if !error.is_empty() {
                eprintln!("error: {error}");
            }
            return ExitCode::from(2);
        }
    };

    match run(options) {
        Ok(()) => ExitCode::SUCCESS,
        Err(error) => {
            eprintln!("error: {error}");
            ExitCode::FAILURE
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn extracts_only_c_fences_with_source_lines() {
        let markdown = "before\n```c\nint a;\n```\n```text\nignored\n```\n```c\nint b;\n```\n";
        assert_eq!(
            extract_c_blocks(markdown).unwrap(),
            vec![
                CBlock {
                    start_line: 3,
                    code: "int a;".to_owned(),
                },
                CBlock {
                    start_line: 9,
                    code: "int b;".to_owned(),
                },
            ]
        );
    }

    #[test]
    fn rejects_unclosed_fence() {
        let error = extract_c_blocks("```c\nint value;\n").unwrap_err();
        assert!(error.contains("line 2"));
    }

    #[test]
    fn escapes_source_paths_for_line_directives() {
        let escaped = c_string_path(Path::new("a\\b\"c.md"));
        assert_eq!(escaped, "a\\\\b\\\"c.md");
    }
}
