#include "fast_polynomial.h"

/*
 * Reverse Bessel polynomial theta_9:
 *
 * x^9 + 45*x^8 + 990*x^7 + 13860*x^6 + 135135*x^5
 *     + 945945*x^4 + 4729725*x^3 + 16216200*x^2
 *     + 34459425*x + 34459425
 */

double fp_eval_p9_horner(double x) {
  double value = x + 45.0;
  value = value * x + 990.0;
  value = value * x + 13860.0;
  value = value * x + 135135.0;
  value = value * x + 945945.0;
  value = value * x + 4729725.0;
  value = value * x + 16216200.0;
  value = value * x + 34459425.0;
  return value * x + 34459425.0;
}

double fp_eval_p9_chain(double x) {
  /*
   * Generated by the paper's rational-preprocessing construction.
   * The five products have multiplicative depth four: t and u are
   * independent once z is available.
   */
  double y = (x + 11.0) * x;
  double z = (x + y - 21.5) * (-x + y + 132.5);
  double t = (x + y + z + 12803.75) * (-x - y + z + 1254.75);
  double u = (y + z + 17266.75) * (-y + z + 1347.75);
  double v = (x + t + 32741929.0) * x;
  return u + v + 56100843.0;
}

long double fp_eval_p9_reference(long double x) {
  long double value = x + 45.0L;
  value = value * x + 990.0L;
  value = value * x + 13860.0L;
  value = value * x + 135135.0L;
  value = value * x + 945945.0L;
  value = value * x + 4729725.0L;
  value = value * x + 16216200.0L;
  value = value * x + 34459425.0L;
  return value * x + 34459425.0L;
}

double fp_eval_x9_horner(double x) {
  double value = x;
  for (int i = 0; i < 8; ++i) {
    value *= x;
  }
  return value;
}

double fp_eval_x9_chain(double x) {
  /*
   * The same five-product construction specialized to P(x) = x^9.
   * It is exact over Q, but the nonzero dyadic constants cancel to recover
   * zero low coefficients. Near x = 0 that cancellation destroys relative
   * accuracy in binary64.
   */
  double y = (x - 0.25) * x;
  double z = (x + y + 0.6484375) * (-x + y + 0.6640625);
  double t = (x + y + z - 0.23040771484375) * (-x - y + z + 0.91607666015625);
  double u = (y + z + 2.37530517578125) * (-y + z - 0.18182373046875);
  double v = (x + t + 0.04570865631103515625) * x;
  return u + v - 0.698051869869232177734375;
}
