if(NOT DEFINED FIXTURE_DIRECTORY)
    message(FATAL_ERROR "FIXTURE_DIRECTORY is required")
endif()

set(manifest "${FIXTURE_DIRECTORY}/manifest.sha256")
file(READ "${manifest}" contents)
string(REPLACE "\n" ";" entries "${contents}")
list(FILTER entries EXCLUDE REGEX "^$")
list(LENGTH entries entry_count)
if(NOT entry_count EQUAL 2)
    message(FATAL_ERROR "expected exactly two frozen format-v1 fixture digests")
endif()

foreach(entry IN LISTS entries)
    if(NOT entry MATCHES "^([0-9a-f]+)  ([A-Za-z0-9_.-]+\\.odt)$")
        message(FATAL_ERROR "invalid fixture manifest entry: ${entry}")
    endif()
    set(expected "${CMAKE_MATCH_1}")
    set(name "${CMAKE_MATCH_2}")
    string(LENGTH "${expected}" digest_length)
    if(NOT digest_length EQUAL 64)
        message(FATAL_ERROR "invalid SHA-256 length for ${name}")
    endif()
    file(SHA256 "${FIXTURE_DIRECTORY}/${name}" actual)
    if(NOT actual STREQUAL expected)
        message(FATAL_ERROR "${name}: expected ${expected}, got ${actual}")
    endif()
endforeach()
